const express = require('express')
const cors = require('cors')
const { dbConnection } = require('./db/config')
require('dotenv').config()
const app = express()
const port = process.env.PORT
dbConnection()
app.use(express.static('public'))
app.use(cors())
app.use(express.json())
app.use('/api/auth', require('./routes/auth'))
app.listen(port, () => console.log(`SERVIDOR CORRIENDO EN EL PUERTO ${port}`))